pdf/contentstream/encoding.go, pdf/core/const.go, pdf/core/encoding.go, pdf/core/stream.go, pdf/model/colorspace.go
See corresponding change in sample code https://github.com/unidoc/unidoc-examples/pull/5
=> Reimplementing dummy colorspaces. See

pdf/contentstream/parser.go
Suggested fix for https://github.com/unidoc/unidoc/issues/103
=> Make parseFloat behave like gs

pdf/creator/chapters.go, pdf/creator/pagebreak.go, pdf/creator/paragraph.go, pdf/creator/table.go
Hello,
This is my first contribution and I do not have deep knowledge about this library. A code review will be appreciated.
=> PageBreak drawable implementation (fixes #86)

pdf/model/annotations.go
AnnotationWidget are usefull for adding Signature widgets
=> Add func NewPdfAnnotationWidget() *PdfAnnotationWidget

pdf/contentstream/contentstream.go
Previously Tm boxes would have their text extracted, but with no
formatting information between boxes. Now, if a box is lower on the
page than has previously been recorded, we insert a newline, and if
a box is further to the right on the same line than a previous box, we
insert a tab character.
This works well enough for parsing Clipper Card transaction histories.
You can see an example at https://clipper-csv.appspot.com.
Fixes #141.
=> ExtractText: handle text matrix (Tm) boxes

pdf/creator/creator_test.go, pdf/creator/paragraph.go, pdf/creator/table.go
Support for wrapping text in Paragraph when placed in a TableCell.
Addresses #166
=> Support wrapped text in table cells

common/license/crypto.go, common/license/key.go, common/version.go, pdf/contentstream/const.go, pdf/contentstream/parser.go, pdf/creator/block.go, pdf/creator/creator.go, pdf/creator/division.go, pdf/creator/drawable.go, pdf/creator/filled_curve.go, pdf/creator/image.go, pdf/creator/paragraph.go, pdf/creator/table.go, pdf/creator/table_test.go, pdf/model/reader.go
Various fixes and additional Division component added to master that will be merged into v3 with this PR.
=> Merge master into v3

pdf/core/primitives.go, pdf/creator/creator.go, pdf/creator/creator_test.go, pdf/model/colorspace.go, pdf/model/optimize/chain.go, pdf/model/optimize/combine_duplicate_direct_objects.go, pdf/model/optimize/combine_duplicate_streams.go, pdf/model/optimize/combine_identical_indirect_objects.go, pdf/model/optimize/compress_streams.go, pdf/model/optimize/image.go, pdf/model/optimize/image_ppi.go, pdf/model/optimize/object_streams.go, pdf/model/optimize/optimizer.go, pdf/model/optimize/options.go, pdf/model/optimizer.go, pdf/model/writer.go
Implemented PDF size optimizations:
- UseCrossReferenceStream (7.5.8 Cross-Reference Streams)
- UseObjectStreams (7.5.7  Object Streams)
- CombineDuplicateDirectObjects
- CombineDuplicateStreams
- ImageQuality
ref #181
=> Implemented : PDFs optimization

pdf/core/parser.go, pdf/model/reader.go
Hello @gunnsth 
Is this any better for the version?
=> Expose PDF Version #230

pdf/creator/block.go, pdf/creator/chapters.go, pdf/creator/const.go, pdf/creator/creator.go, pdf/creator/creator_test.go, pdf/creator/curve.go, pdf/creator/curve_test.go, pdf/creator/division.go, pdf/creator/division_test.go, pdf/creator/ellipse.go, pdf/creator/filled_curve.go, pdf/creator/filled_curve_test.go, pdf/creator/image.go, pdf/creator/line.go, pdf/creator/pagebreak.go, pdf/creator/paragraph.go, pdf/creator/rectangle.go, pdf/creator/styled_paragraph.go, pdf/creator/styled_paragraph_test.go, pdf/creator/subchapter.go, pdf/creator/table.go, pdf/creator/table_test.go, pdf/creator/text_style.go, pdf/creator/toc.go, pdf/creator/toc_line.go, pdf/creator/toc_test.go
- Allows new components to be created only through the creator component
- Adds default fonts which are shared between all the components (default font caching)
- Fixes font naming scheme and resolves issue #222
- Fixes existent golint errors
- A couple of more fixes in the paragraph and blocks components
=> Create components through the creator

pdf/creator/creator_test.go, pdf/model/font_composite.go, pdf/model/textencoding/simple.go
* Correctly enumerate runes in font.
* Load font only once in `TestParagraphChinese`.
* Few stylistic and portability changes.
=> Minor fixes to font packages

Jenkinsfile, pdf/core/primitives.go, pdf/model/colorspace.go, pdf/model/const.go
=> Colorspace parsing fix when name embedded in indirect object

Jenkinsfile, pdf/contentstream/encoding.go, pdf/contentstream/inline-image.go
Added references and cleaned up style.
=> Support more full name params in inline images.  Fixes #235

pdf/creator/creator.go, pdf/creator/list.go, pdf/creator/list_test.go, pdf/creator/table.go, pdf/creator/utils.go
This pull requests adds a configurable list component (similar to HTML's ul).
Addresses issue #83.
=> Add list component

pdf/creator/creator_test.go, pdf/model/font_composite.go
=> Make PDF output stable when using custom fonts

Jenkinsfile
=> Require extractor private testdata in builds

pdf/internal/textencoding/differences.go, pdf/internal/textencoding/simple.go
This PR allows merging differences maps if `ApplyDifferences` is called twice, and fixes #293.
=> Fix differences

pdf/creator/invoice.go
Fixes invoice notes section not being left aligned with the rest of the layout.
Resolves #302
=> Fix invoice notes section alignment

CONTRIBUTING.md, README.md, common/version.go, pdf/contentstream/encoding.go, pdf/contentstream/inline-image.go, pdf/core/primitives.go, pdf/model/colorspace.go, pdf/model/const.go
Prior to releasing v3.0.0-alpha.1, merging in master.
=> Merge master into v3 prior to release

codecov.yml
Disable patch and changes status fails.
Set baseline for project test coverage.
=> Add codecov.yaml configuration in v3

pdf/core/encoding.go, pdf/model/colorspace.go, pdf/model/image.go, pdf/model/optimize/image_ppi.go, pdf/model/xobject.go
Fixes various scenarios in which the optimizer freezes or distorts the original PDF images.
Resolves #322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unidoc/331)
=> Compression issues

pdf/core/const.go, pdf/core/crossrefs.go, pdf/core/encoding.go, pdf/core/parser.go, pdf/core/repairs.go, pdf/core/symbols.go
=> Fix golint notices in the core package

pdf/creator/chapters.go, pdf/creator/creator_test.go
Add styled paragraph support for the creator chapter component.
Resolves #368
=> Chapters styled paragraph support

pdf/model/colorspace.go, pdf/model/font.go, pdf/model/fontfile.go, pdf/model/functions.go, pdf/model/image.go, pdf/model/internal/fonts/ttfparser.go, pdf/model/outlines.go, pdf/model/page.go, pdf/model/pattern.go, pdf/model/reader.go, pdf/model/resources.go, pdf/model/shading.go, pdf/model/structures.go, pdf/model/writer.go, pdf/model/xobject.go
=> Fix golint notices in the model package

pdf/creator/creator_test.go, pdf/creator/paragraph.go
Use creator's default font as the default font of the Paragraph component, thus avoiding creating a new font instance whenever a new Paragraph instance is created.
Addresses #382
=> Paragraph cache default font

pdf/creator/table.go, pdf/creator/table_test.go
Add SetHeaderRows method to the Table component which turns a range of rows into table headers, repeated on page break.
Addresses #386
=> Add table headers support

Jenkinsfile
Update to an installed golang version on the build server.
=> Update Jenkinsfile go version [master]

pdf/creator/styled_paragraph.go, pdf/creator/styled_paragraph_test.go, pdf/creator/utils.go
Rotate link annotation rectangles when paragraph is rotated.
Addresses #406
=> Styled paragraph link rotation

pdf/model/sighandler/sighandler_rsa_sha1.go
Allow specifying a custom signing function for the adobeX509RSASHA1 signature handler
=> Add custom signing function for the adobeX509RSASHA1 signature handler

pdf/model/reader.go
=> Set Pages dict Type if not set

pdf/model/reader.go
=> Make outline root an indirect object if it is a dict

pdf/contentstream/draw/bezier_curve.go, pdf/contentstream/draw/path.go, pdf/contentstream/draw/point.go, pdf/contentstream/draw/shapes.go, pdf/contentstream/draw/vector.go
=> Golint contentstream draw

pdf/model/reader.go
=> Account for page count being a reference in the reader

pdf/core/security/crypt/filter_aesv2.go, pdf/core/security/crypt/filter_aesv3.go
=> Account for crypt filter length specified in bits for AESV2 and AESV3

pdf/model/fields.go
=> Make T field optional on PDF field dictionary parse

pdf/model/annotations.go, pdf/model/fields.go, pdf/model/page.go, pdf/model/writer.go, pdf/model/writer_test.go
=> V3: Write page annots from loaded PDFs
