unidoc/unidoc

- pdf/crossrefs.go
- pdf/pdfparser.go
- pdf/reader.go
- pdf/repairs.go
- pdf/writer.go
Ticket UD-42 (JIRA).  Repairs files with broken xref structure.  Including a few different scenarios.
- If missing startxref, attempts to locate the nearest line starting with "xref" and load the xref table.
- If an xref offset points to a location where there is no object, then attempts a repair by parsing from top to bottom
- If an xref entry points to an object with a different number then attempts to repair the numbering
Also cleaned up some code, such as an unnecessary list of nofollow items.
> UD-42 (Repair broken xrefs)

- pdf/contentstream/inline-image.go
- pdf/contentstream/processor.go
- pdf/core/encoding.go
- pdf/core/encoding_test.go
- pdf/core/parser_test.go
- pdf/core/stream.go
- pdf/model/colorspace.go
- pdf/model/resources.go
- pdf/model/xobject.go
This is a cleaned up version of https://github.com/unidoc/unidoc/pull/93
Changes needed to make pdf_describe.go example work
Extract decodeParam when they are in a 1-element array
Changes to make shamirturing.pdf pass pdf_describe.go
Fixed a buffer overrun seen in my testing on ESCP-R reference_151008
Changes to make a_im_nomask.pdf pass pdf_describe.go 
Changes to make shattered-1.pdf pass pdf_describe.go 
Changes to make 1986-jacm.pdf pass pdf_describe.go 
 Added a run length encode filter
> Fixed some bugs found while getting pdf_descibe.go to work

- pdf/creator/paragraph.go
The content of the struct field Paragraph.textLines must be not encoded with the text encoder because after the method drawParagraphOnBlock encodes it again.
It is useless to say that twice encoding on the same text portion gives troubles :)
Illustration of the issue : 
```go
package main
import (
"io/ioutil"
"os"
"fmt"
"github.com/unidoc/unidoc/common"
"github.com/unidoc/unidoc/pdf/creator"
)
func main() {
f, err := ioutil.TempFile(os.TempDir(), "pdf")
if err != nil {
panic(err)
}
common.SetLogger(common.NewConsoleLogger(common.LogLevelDebug))
c := creator.New()
t := creator.NewTable(1)
cell := t.NewCell()
cell.SetContent(creator.NewParagraph("this is a special char ß"))
err = c.Draw(t)
if err != nil {
panic(err)
}
err = c.Write(f)
if err != nil {
panic(err)
}
fmt.Println(f.Name())
}
``` …
> Text wrapping : dont encode p.textLines

- pdf/contentstream/contentstream.go
- pdf/contentstream/contentstream_test.go
When text is part of a `TJ` operand, `ContentStream.ExtractText` concatenates all of the `PDFObjectString`s that it finds. However, the `TJ` operator may perform glyph positioning, and ignoring this positioning results in spaces being ignored. For example, see the output of the text extraction example program at https://unidoc.io/examples/text/extract-text-in-pdf when applied to the paper https://research.google.com/pubs/pub43146.html.
This implements a simple way to handle glyph positioning inserting a space when the offset exceeds a hard-coded amount.
Is there a way to do this considering previous `Tc` and `Tw` operators?
> Insert a space when TJ string is offset by more than a threshold

- pdf/creator/creator.go
There was no obvious way to pass a populated PdfAcroForm to the underlying PdfWriter.  This code adds acroForm *model.PdfAcroForm and SetForms to Creator.  
Populating the PdfAcroForm is left to the user to implement.  But once populated, this enhancement allows you to write the PDF with the form fields filled in.
> Added SetForms to Creator, giving the ability to fill in form fields

- pdf/model/reader.go
I chose to return an error if the user passes pageNumber = 0 to prevent a panic.  However, it may be more intuitive to start the page numbers from 0.
> Fix #131: Return error on pageNumber = 0

- pdf/core/parser.go
- pdf/core/parser_test.go
- pdf/core/symbols.go
- `bytes.Buffer` used instead of collecting result in `string` or `[]byte`
- faster skipping whitespace in `parseHexString`, relaying str -> hex conversion to base library
- added benchmarks to test suite
Results:
- `parseName` 26850ns/op 359alloc => 17464ns/op 95alloc
- `parseHexString` 17251ns/op 13alloc => 10700ns/op 10alloc
Other touched functions gain around 5-10%
> Parser crude optimizations.

- pdf/internal/cmap/utils.go
when not use uint64 to change, the val calculated will not be correct which make the map of cmap failed
> bugfix for cal code val

- pdf/internal/cmap/cmap.go
when j reach to MaxLen or len(src) to jump, it will jump one more character which affect the parse afterward
> bugfix for parse

- pdf/model/font_simple.go
I found out why setting a default font encoding of "StandardEncoding" works. This is the resulting update to the comments.
> Explain Fall back to StandardEncoding.

- common/license/util.go
This is to make the license information more verbose. Breaking change.
> Adding customerName parameter to SetLicenseKey

- pdf/core/crypt.go
- pdf/core/crypt_test.go
- pdf/core/primitives.go
- pdf/model/writer.go
PR implements the AESv3 (R=5-6) encryption.
It also exposes encryption algorithms AESv2 (128 bit, R=4) and AESv3 (256 bit, R=6 only) to the user by adding an `Algorithm` option to `EncryptionOptions`.
Resolves #198.
> Implement AES encryption (128 and 256 bits)

- pdf/core/crypt.go
- pdf/core/parser.go
According to spec, XRefs and "Encrypt" dictionary should never be decrypted.
Currently, the library attempts to decrypt them if trying to iterate over all objects in PDF, as described in #205.
This change records a reference to "Encrypt" dictionary in `Decrypted` map, so it won't be passed to decryption routine.
It also checks the `Type` field of `PdfObjectStream` and skips decryption if it's an `XRef` stream.
PR also includes a small refactoring for Encrypt and Decrypt function.
> Do not decrypt XRef streams and "Encrypt" dictionary

- pdf/core/crypt.go
- pdf/core/crypt_file_test.go
- pdf/core/parser.go
PR adds better tests for decryption of documents and fixes a few issues discovered by the test.
* Do not decrypt "Info" and "Encrypt" dictionaries in the trailer.
* Decrypt XRef streams only for R=5
> Correctly handle decryption of XRef streams and trailer fields

- pdf/creator/styled_paragraph.go
Fixes a typo which causes text wrapping on newline character to work incorrectly.
> Fix styled paragraph newline text wrapping

- pdf/creator/creator_test.go
- pdf/creator/division_test.go
- pdf/creator/paragraph.go
- pdf/creator/styled_paragraph.go
- pdf/creator/table.go
Wrap text in paragraph/styled paragraph only if wrapping is enabled and the wrap width is larger than 0.
Enable paragraph/styled paragraph wrapping by default.
> Wrap paragraph text only if width has been set

- pdf/core/security/handlers.go
- pdf/core/security/standard_r4.go
- pdf/core/security/standard_r6.go
* Remove panics from R=6 security handlers, validate fields before using.
* Simplify the code of R=4 security handlers (replace loops with stdlib functions).
> Remove panics from crypto code, simplify the code

- pdf/internal/textencoding/encoder.go
- pdf/internal/textencoding/identity.go
- pdf/internal/textencoding/simple.go
- pdf/internal/textencoding/truetype.go
* Unify character encoding functions and document their expectations.
* Replace `Sscanf` in `IdentityEncoder.GlyphToCharcode` with `ParseUint`.
> Minor improvements to the fonts encoders

- pdf/model/fonts/ttfparser.go
- pdf/model/fonts/ttfparser_test.go
Backport few fixes to the `font` package discovered while testing against `x/image/font` library:
* Remove `Embeddable` field from `TtfType` (unused)
* Fix bounds check in GID-to-names mapper (unsigned < zero)
* Fix `ItalicAngle` value (floats are signed)
* Add tests for the TTF parser
> TTF parser fixes and tests

- pdf/model/font_composite.go
- pdf/model/font_simple.go
- pdf/model/fonts/ttfparser.go
- pdf/model/fonts/ttfparser_test.go
Currently, the code reads TTF file twice: once to parse it and the second time to embed it into the PDF. This PR changes it to read the file once and reuse the data to parse and embed the font.
> Read TTF font data once

- pdf/creator/invoice_test.go
- pdf/creator/table.go
Resolves #299
The issue this pull request fixes can be easily reproduced by having a table spanning multiple pages that does not start at the top of the page it's currently drawn on (it has some other components above it on that page). 
In this scenario, the total height of new pages is based on the height of the page the table starts on (which is not a complete page)
> Multipage table fix

- pdf/creator/chapters.go
- pdf/creator/creator.go
- pdf/creator/subchapter.go
- pdf/model/outline.go
- pdf/model/outlines.go
Generate PDF outlines automatically for Chapter and Subchapter components in the Creator.
Also, adds a high level interface for creating outline trees in the model package, compatible with the
low level interface.
Resolves #87 
Resolves #14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unidoc/321)
> Add Creator support for outlines

- Jenkinsfile
- codecov.yml
- pdf/internal/e2etest/allobjects_test.go
- pdf/internal/e2etest/passthrough_test.go
- pdf/internal/e2etest/validate.go
Package e2etest implements integration tests with a small test corpus (externally provided).  It currently has two tests:
- Passthrough, which loads a PDF with unidoc, and writes back out and optionally validates with ghostscript ensuring that no errors are added by unidoc.
- Allobjects which combs through all streams in the PDF and decodes, ensuring that there are no errors.
In the future we will add more integration test coverage and validation that the output is as expected.  The current integration tests only ensure that there are no errors in loading, and outputing.
Added to Jenkinsfile to run in automatic builds and test coverage measurements.  The test coverage is now obtained with
```
go test -coverprofile=coverage.out -covermode=atomic -coverpkg=./... ./...
```
which measures the …
> Integration test coverage

- pdf/extractor/image.go
- pdf/extractor/image_test.go
- pdf/model/colorspace.go
Fix and test for ICC color spaces without default ranges.
I found this bug while testing the new image position code and added a test function to regression test it.
> V3.imagemark

- pdf/creator/const.go
- pdf/creator/styled_paragraph.go
- pdf/creator/styled_paragraph_test.go
- pdf/creator/text_style.go
Adds rendering mode field to the TextStyle structure. Also adds text chunks with different rendering modes  to the StyledParagraph component.
Should resolve #221
> Add text style rendering mode

- pdf/creator/styled_paragraph.go
- pdf/creator/styled_paragraph_test.go
- pdf/creator/text_style.go
Add TextStyle character spacing field.
Integrate character spacing into the StyledParagraph component.
Resolves #119
> Character spacing

- pdf/model/functions.go
- pdf/model/functions_test.go
- pdf/model/image.go
- pdf/model/outlines.go
- pdf/model/page.go
- pdf/model/page_test.go
- pdf/model/pattern.go
- pdf/model/reader.go
- pdf/model/resources.go
- pdf/model/shading.go
- pdf/model/structures.go
- pdf/model/writer.go
- pdf/model/xobject.go
Removes dot imports from the model package. (I did not find any others using them)
Resolves #309
> Remove dot imports

- pdf/model/appearance.go
- pdf/model/appender.go
- pdf/model/fields.go
- pdf/model/sighandler/sighandler_pkcs7.go
- pdf/model/sighandler/sighandler_rsa_sha1.go
- pdf/model/signature.go
- pdf/model/signature_handler.go
- pdf/model/writer.go
> Signature support refactoring

- pdf/core/primitives.go
Before this change `optimize.(*CombineDuplicateDirectObjects).Optimize` has spent 97% of it's runtime in `github.com/unidoc/unidoc/pdf/core.(*PdfObjectDictionary).WriteString` and optimising a 500 page PDF with 4 images / page took a couple minutes on 8-thread cpu
After the change it's <1% and optimising the same file takes seconds.
> Reduce memory thrashing when optimising large PDFs

- pdf/annotator/field_appearance.go
- pdf/annotator/form_field.go
- pdf/model/appender.go
- pdf/model/appender_test.go
- pdf/model/fields.go
Add text based signature appearance.
Addresses #340 and #323 (except for the signature appearance image support which will be addressed in another PR)
> Signature appearance

- pdf/model/appender.go
- pdf/model/signature.go
- Remove duplicate code in Signature model ToPdfObject
- Update signature object ByteRange field in the appender write method
> Signature refactoring

- pdf/extractor/image.go
- pdf/extractor/image_test.go
- Add options to ExtractPageImages extractor method
- Skip extraction of inline stencil masks by default
Resolves #362
> Add image extraction options

- pdf/core/primitives.go
Replace fmt.Sprintf with strings.Builder and strconv conversions.
Resolves #348 
Benchmarks (ran on development computer):
Before
```
BenchmarkPdfObjectIntegerWriteString-8      	10000000	       106 ns/op
BenchmarkPdfObjectFloatWriteString-8        	 5000000	       257 ns/op
BenchmarkPdfObjectStringWriteString-8       	   10000	    113057 ns/op
BenchmarkPdfObjectNameWriteString-8         	  500000	      3190 ns/op
BenchmarkPdfObjectArrayWriteString-8        	      20	 100750574 ns/op
BenchmarkPdfObjectDictionaryWriteString-8   	     200	   6185730 ns/op
BenchmarkPdfObjectReferenceWriteString-8    	10000000	       162 ns/op
BenchmarkPdfIndirectObjectWriteString-8     	10000000	       109 ns/op
BenchmarkPdfObjectStreamWriteString-8       	10000000	       110 ns/op …
```
> Optimize WriteString method for primitive objects

- pdf/core/crossrefs.go
- pdf/core/parser.go
- pdf/core/parser_test.go
Bug when parsing "0" in parseObject() would return an EOF error.
Testcase added.
> Fix parsing bug for single-digit integer

- pdf/contentstream/draw/point.go
- pdf/creator/const.go
- pdf/creator/creator_test.go
- pdf/creator/image.go
- Adds creator HorizontalAlignment type (used only for images at the moment)
- Make rotation origin the center of the image
- Fix relative mode rotated images placement
Addresses #85
> Image horizontal alignment

- pdf/core/encoding.go
- pdf/model/annotations.go
- pdf/model/page.go
- pdf/model/reader.go
- pdf/model/signature.go
Fixes for loading various corpus PDF files that can be loaded by ghostscript.  Addresses 4 error types that were seen.
- invalid-attribute
- invalid-decode-params
- not-a-dictionary-object
- unknown-annotation-linkid
> Fix incompatibility errors when loading various corpus PDF files [v3]

- pdf/core/parser.go
- pdf/core/parser_test.go
Addresses 2 errors encountered in corpus PDF files.
> Parsing compatibility fixes [v3]

- pdf/model/font_test.go
- pdf/model/internal/fonts/std.go
Use regular `space` character metrics for the `no-break space` character if nbsp handling is not already defined.
Addresses #396
> No break space character metrics

- pdf/creator/table.go
- pdf/creator/table_test.go
Add ability to copy a table onto another table, at a specified position.
Addresses #395
> Implement AddSubtable method for the Table component

- pdf/creator/table.go
- pdf/creator/table_test.go
> Add Rows and Cols methods to the Table component

- pdf/creator/table.go
- pdf/creator/table_test.go
- Copy row height when adding subtables
- Add GetRowHeight method to the Table component
Addresses #403
> Subtable row height

- Jenkinsfile
- pdf/internal/e2etest/memory_measure.go
- pdf/internal/e2etest/split_test.go
- pdf/internal/e2etest/utils.go
The split test reads and writes back out a single page from each test file.
Tests the efficiency of working with parts of large files.
Checks the hash of the output to avoid regressions.
Measures duration and memory allocations.
> Add split e2e test with memory checking [v3]

- pdf/core/security/crypt/filter_aesv3.go
Addresses #412 
- Fix when padLen == len(buf). Allows to clear entire buffer.
> Fix invalid pad length [v3]

- Jenkinsfile
Errors when trying to compile new pkcs11 signature examples with cgo disabled.  This addresses that and specifically enables cgo where needed.
> Fix v3 build: Compile pkcs11 examples with cgo enabled

- pdf/contentstream/const.go
- pdf/contentstream/inline-image.go
- pdf/contentstream/parser.go
- pdf/contentstream/processor.go
Fix golint notices in the contentstream package.
Addresses #421
> Fix contentstream package golint notices

- Jenkinsfile
- pdf/core/crossrefs.go
- pdf/core/crossrefs_test.go
- pdf/core/crypt_test.go
- pdf/core/fuzz_test.go
- pdf/core/parser.go
- pdf/core/parser_test.go
- pdf/core/repairs.go
- pdf/core/utils.go
- pdf/model/writer.go
Two notable performance enhancements:
- xrefNextObjectOffset search changed to binary search and limited to only uncompressed objects (ones with offset and not within stream).
- Speedup hasObject lookup in the writer using a map.
Changes required changing XrefTable to a struct to be able to add the cached list of objects for faster search.
The changes speed up passthrough benchmark test in the build server from 38-40seconds down to 15 seconds, so it's a pretty significant improvement.
> Cross reference search speed improvements [v3]

- pdf/internal/e2etest/split_test.go
- pdf/model/writer.go
Fixes build tests that were failing in hash comparison as version string had changed.
> Make e2e split test version independent

- pdf/core/encoding.go
- pdf/core/parser.go
- pdf/core/parser_test.go
- pdf/model/writer.go
Addresses #445 . Currently empty objects are parsed as *PdfIndirectObject with an inner object (PdfObject) as nil. This can cause errors down the line.
Such an empty indirect object is not technically valid but still appears out in the wild. It should be safe to treat these as null objects and output an incompatibility warning.
In addition, this PR checks for the nil object when writing out and sets it.  Thus the safeguarding is done both on parsing and writing out.
This PR also updates `ParseIndirectObject` to enable handling of short objects. Previously an EOF error was returned if less than 20 bytes in length and the parsing not finished.
> Parser: Treat empty indirect objects as containing the null object

- pdf/core/io.go
- pdf/core/parser.go
Search for xref objects on both directions with 20 bytes tolerance.
Reset to the current offset after reading the content.
Addresses #433
> Search xref objects with tolerance both to the left and right

- pdf/model/image.go
- pdf/model/image_test.go
Addresses #444 .
The problem is that loaded Go images have a data buffer that is not always of the same format, there can be extra bytes at the end of each line (image.Stride != bytesPerPixel*pixelsPerLine).
This was assumed to be the case, but was not, leading to some offsets building up and image distortion.
This PR addresses the problem by redrawing the images onto a "canvas" of the right size such that the new image has the right format. The drawback is that redrawing the image means that the image is loaded into memory twice so that doubles the memory use as a result (and obviously takes more time too).
The alternative approach would have been to alter model.Image to have a Stride parameter similarly to the original go image.  That would require a lot more changes in internal data …
> V3: Detect and fix stride offsets in loaded go images

- pdf/creator/block.go
- pdf/creator/paragraph_test.go
Demonstrates issue #139. Couple of TODO comments to where things appear to be slow.
Results:
```
pkg: github.com/unidoc/unidoc/pdf/creator
BenchmarkParagraphAdding1-8             Unlicensed copy of unidoc
2000            878991 ns/op
BenchmarkParagraphAdding10-8            Unlicensed copy of unidoc
300           6307502 ns/op
BenchmarkParagraphAdding100-8           Unlicensed copy of unidoc
10         103607560 ns/op
PASS
ok      github.com/unidoc/unidoc/pdf/creator    5.440s
```
Very slow and seems to get worse with increasing number of paragraphs.
Also did some profiling of code that added many paragraphs (5000).  That took a few minutes to process.
The profiling output (top 100) below indicates a lot of work being spent in processing the contents.
This is probably because a lot of …
> Creator: Benchmark for paragraph adding
